services:
  db:
    image: postgres:17.2
    container_name: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    container_name: web
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
